import type { Metadata } from "next";
import "./globals.css";
import { doranlight } from "@/next-persian-fonts/doran";
import Navbar from "@/components/global/navbar";
import Footer from "@/components/global/footer";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "MSL - Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${doranlight.className} antialiased relative`}>
        {/* <Navbar /> */}
        <Toaster />
        {children}
        <Footer />
      </body>
    </html>
  );
}
