import type { Metadata } from "next";
import "./globals.css";
import { doranregular } from "@/next-persian-fonts/doran";
import Navbar from "@/components/global/navbar";
import Footer from "@/components/global/footer";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "MSL - Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     

      <body
        className={` ${doranregular.className} bg-[#e5d8d0] antialiased relative`}
      >
        <Navbar />
        <ToastContainer position="top-center" rtl={true} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
